---
- name: Playbook
  hosts: webserver
  become: yes
  become_user: root
  tasks:
    - name: Create new user
      user:
        name: newuser
    - name: Create .ssh folder
      file:
        path: ~newuser/.ssh
        state: directory
        owner: newuser
        group: newuser
        mode: 0700
    - name: Upload autherize_key key
      copy:
       src: keys/newuser
       dest: ~newuser/.ssh/authorized_keys
       owner: newuser
       group: newuser
       mode: 0700
